#ifndef LEXICOGRAPHICAL_BLOCK_DELIMITER
#define LEXICOGRAPHICAL_BLOCK_DELIMITER "#ORDEM"
#endif

#ifndef TEXT_BLOCK_DELIMITER
#define TEXT_BLOCK_DELIMITER "#TEXTO"
#endif

#ifndef ALPHABET_DEFAULT_SIZE
#define ALPHABET_DEFAULT_SIZE 26
#endif

#ifndef ASCII_OF_FIRST_LETTER
#define ASCII_OF_FIRST_LETTER 65
#endif

#ifndef ASCII_OF_LAST_LETTER
#define ASCII_OF_LAST_LETTER 122
#endif

#ifndef FIRST_WORD_IS_GREATER
#define FIRST_WORD_IS_GREATER 1
#endif

#ifndef SECOND_WORD_IS_GREATER
#define SECOND_WORD_IS_GREATER 2
#endif

#ifndef NONE_OF_WORDS_IS_GREATER
#define NONE_OF_WORDS_IS_GREATER 0
#endif